import Link from 'next/link';

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 to-teal-50 relative selection:bg-teal-200 text-slate-900 pb-20 overflow-x-hidden pt-24 px-4">
            {/* Decorative background blobs */}
            <div className="absolute top-[-10%] left-[-10%] w-96 h-96 bg-emerald-200 rounded-full mix-blend-multiply filter blur-3xl opacity-50 pointer-events-none"></div>
            <div className="absolute top-[20%] right-[-5%] w-72 h-72 bg-teal-200 rounded-full mix-blend-multiply filter blur-3xl opacity-50 pointer-events-none"></div>

            <div className="max-w-4xl mx-auto relative z-10 bg-white/70 backdrop-blur-lg rounded-3xl p-8 md:p-12 shadow-xl border border-white/40">
                <h1 className="text-4xl md:text-5xl font-black text-slate-800 mb-8 border-b-2 border-teal-100 pb-4">
                    Terms of Service
                </h1>

                <div className="prose prose-teal max-w-none text-gray-600 leading-relaxed space-y-6">
                    <p className="font-medium text-sm text-gray-500 mb-8">
                        Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                    </p>

                    <h2 className="text-2xl font-bold text-slate-800 mt-8 mb-4">1. Acceptance of Terms</h2>
                    <p>
                        By accessing and using the Macro & Inflammation Estimator, a service owned and operated by The Iyer Group, LLC (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
                    </p>

                    <div className="bg-red-50 border border-red-200 rounded-xl p-6 my-8">
                        <h2 className="text-2xl font-bold text-red-800 mb-4 mt-0">2. Medical & Health Disclaimer</h2>
                        <div className="space-y-4 text-red-900">
                            <p>
                                <strong>NOT MEDICAL ADVICE:</strong> The Macro & Inflammation Estimator, including all text, graphics, algorithms, calculations, and other material contained within the application, are for informational and educational purposes only.
                            </p>
                            <p>
                                The results generated by this tool do not constitute professional medical advice, diagnosis, or treatment. Never disregard professional medical advice or delay in seeking it because of something you have read or calculated on this Website.
                            </p>
                            <p>
                                <strong>ALGORITHMIC METHODOLOGY:</strong> While our core algorithms and nutritional models are developed in consultation with experienced medical professionals—including those with experience from some of the world's most prestigious medical programs and institutes—the resulting baseline estimates are generic and not tailored to your complete individual medical history. You should always consult with a qualified healthcare provider or registered dietitian before making any significant dietary changes, especially if you have existing health conditions.
                            </p>
                        </div>
                    </div>

                    <h2 className="text-2xl font-bold text-slate-800 mt-8 mb-4">3. Use License</h2>
                    <p>
                        Permission is granted to temporarily use the materials on our website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Modify or copy the materials.</li>
                        <li>Use the materials for any commercial purpose, or for any public display (commercial or non-commercial).</li>
                        <li>Attempt to decompile or reverse engineer any software contained on the website.</li>
                        <li>Remove any copyright or other proprietary notations from the materials.</li>
                    </ul>

                    <h2 className="text-2xl font-bold text-slate-800 mt-8 mb-4">4. Limitations of Liability</h2>
                    <p>
                        In no event shall The Iyer Group, LLC or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption, or personal injury/health complications) arising out of the use or inability to use the materials on our algorithmic models, even if we have been notified orally or in writing of the possibility of such damage.
                    </p>

                    <h2 className="text-2xl font-bold text-slate-800 mt-8 mb-4">5. Accuracy of Materials</h2>
                    <p>
                        The materials appearing on the website could include technical, typographical, or photographic errors. We do not warrant that any of the materials on its website are accurate, complete, or current. We may make changes to the materials contained on its website at any time without notice.
                    </p>

                    <h2 className="text-2xl font-bold text-slate-800 mt-8 mb-4">6. Links</h2>
                    <p>
                        We have not reviewed all of the sites linked to our website and are not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by us of the site. Use of any such linked website is at the user's own risk.
                    </p>

                    <h2 className="text-2xl font-bold text-slate-800 mt-8 mb-4">7. Contact Information</h2>
                    <p>
                        If you have any questions about these Terms, please contact us at hello@macroinflammationcalculator.com. You can also review our <Link href="/privacy" className="text-teal-600 hover:underline">Privacy Policy</Link> for information on how we handle user data.
                    </p>
                </div>
            </div>
        </div>
    );
}
